### ISSUE TITLE
使用过程中的一些疑惑与思考

### ISSUE THREAD

**Issue by galaxyxxxxx** [tsosunchia/bjut_autosignin#1]
- branch1中 通过学号+密码登陆的链接，目前似乎`重置了密码`，尝试了十余次密码，暂未成功登入。因此，难以使用第一种方式进行打卡。

- branch2中 在您的代码基础上，对打卡数据加入个人信息并重新编码，但最后打卡失败，返回了501😅，暂时未排查到问题所在，希望能向您请教！

- 此外，关于自动打卡，看到您在readme中标注可以通过阿里云云函数定时调用。或许使用Github Actions即可完成同样的效果，不妨一试:)

关于以上问题，希望能与您继续探讨！☺️

**Comment by tsosunchia** [comment]
关于branch1 最近网站升级了一次大多数人的密码都与xgxt.bjut.edu.cn不一样了，所以建议弃用
关于branch2，不知道你的意思是否是更改了post data中数据，如果是的话建议通过charles等专业http抓包软件compose你抓到的包，然后copy raw中的数据即可
关于第三个问题 GitHub的这个功能虽然我没用过但我相信确实可以达到相同效果，文中举例的阿里云是为了方便没有翻墙环境的同学，如果能翻墙其实我更推荐Google云的函数功能也是免费，被查水表的风险更小

**Comment by galaxyxxxxx** [comment]
嗯嗯，目前在用branch2的方式的，并且基于branch2重新整理了一份脚本放在[这里](https://github.com/galaxyxxxxx/auto-clock-in)，提取了个人信息模块并采用github actions进行每日定点打卡与发送邮件通知。

关于id和token有效期仅7天，想咨询一下这个时长是如何获取到的呢～😊

**Comment by tsosunchia** [comment]
"关于id和token有效期仅7天" 抓包时从set-cookie项即可获得（企业微信每次重新登录或者上次的token过期时服务器会发送一个包headers中包含

**Comment by tsosunchia** [comment]
最近的更新解决了一些紧要的问题你可以看一下
